# Generated by Django 4.2.7 on 2024-10-12 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.CharField(max_length=15, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Declined', 'Declined'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes')),
                ('prep_time', models.IntegerField()),
                ('cook_time', models.IntegerField()),
                ('ready_in', models.IntegerField()),
                ('servings', models.IntegerField()),
                ('recipe_yield', models.IntegerField()),
                ('skill_level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Advanced', 'Advanced')], default='Medium', max_length=20)),
                ('video_link', models.CharField(max_length=20)),
                ('calories', models.CharField(max_length=15)),
                ('carbohydrates', models.CharField(max_length=15)),
                ('fat', models.CharField(max_length=15)),
                ('protein', models.CharField(max_length=15)),
                ('cholestrol', models.CharField(max_length=15)),
                ('dietary_fiber', models.CharField(max_length=15)),
                ('rating', models.FloatField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('course', models.CharField(choices=[('main_course', 'Main Course'), ('side_dish', 'Side Dish'), ('desert', 'Desert'), ('snack', 'Snack')], default='main_course', max_length=20)),
                ('cuisine', models.CharField(choices=[('Italian', 'Italian'), ('French', 'French'), ('Chinese', 'Chinese'), ('Indian', 'Indian'), ('Mexican', 'Mexican')], default='Italian', max_length=20)),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approver_recipes', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_recipes', to='recipe.category')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chef_recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
