# Generated by Django 4.2.7 on 2024-10-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='video_link',
            field=models.CharField(max_length=100),
        ),
    ]
