# Generated by Django 4.2.7 on 2024-10-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
