# Generated by Django 4.2.7 on 2024-10-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_recipe_admin_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_of_the_day',
            field=models.BooleanField(default=False),
        ),
    ]
