# Generated by Django 4.2.7 on 2024-10-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='short_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
